version: '3.1'
services:
  main:
    build: .
    container_name: main
    volumes:
      - ./:/go/src/ethereum_client
    command: bash -c "
      bash /go/src/ethereum_client/ganache.sh
      && go run /go/src/ethereum_client/cmd/clientd/main.go
      "
      

  test:
    build: .
    container_name: test_runner
    volumes:
      - ./:/go/src/ethereum_client
    command: go test 
